### ISSUE TITLE
wmake: no member found

### ISSUE THREAD

**Issue by phileuringer** [petebachant/kOmegaSSTLowRe#6]
Hi everyone

I am trying to change my Turbulence model from kOmegaSST to kOmegaSST for low Re.
I am using OpenFoam 3.01 on Centos 7. 

Unfortunately, when I tried to run 'wmake libso' I got some issues running the model. Please have a look at the attached terminal screenshot.

![error_msg](https://user-images.githubusercontent.com/39858288/40877331-8bd5dbc0-667f-11e8-91ff-d78ec9165897.PNG)

I am quite new to OpenFoam so I don't really know how to fix these errors.

May I get some advice, so I can implement the model :)

I am thankful for anything I get!

Regards

Philipp

**Comment by petebachant** [comment]
I'm going to assume this was introduced by https://github.com/petebachant/kOmegaSSTLowRe/commit/2c69a55826e4d98e3ff57741c733a5faf4f4f040. Are you absolutely tied to OpenFOAM 3.0.1? If so you can check out commit 058e6158 (`git checkout 058e6158 `) and it will likely build then.

**Comment by phileuringer** [comment]
Thank you so much!
It worked perfectly!
