### ISSUE TITLE
References

### ISSUE THREAD

**Issue by GontzalLopez** [petebachant/kOmegaSSTLowRe#7]
HI @petebachant,

Could you provide me with the reference you used to implement the equations? 

The only references I have found are those related with the low Reynolds implementation of the standard k-omega model as in Fluent:
https://www.afs.enea.it/project/neptunius/docs/fluent/html/th/node66.htm#alpha_star

However I'm interested in the original equations you used for the low Reynolds k-omega SST. 

regards

**Comment by GontzalLopez** [comment]
I found it here: https://turbmodels.larc.nasa.gov/wilcox.html

**Comment by petebachant** [comment]
I actually didn't write this implementation as noted in the README. I just packaged it up. Sounds like you found what you were looking for though!
